### ISSUE TITLE
Hyper error: invalid domain character (None)

### ISSUE THREAD

**Issue by ckmro-labs** [databricks/click#136]
Rust 1.14.1
System: MacOS Catalina
Kube's Context config like this:  

server: https://192.168.0.132:6443

issue: when I get source build or cargo install click, command nodes error: Hyper error: invalid domain character (None), kubectl is valid.

**Comment by nicklan** [comment]
This should be fixed by the new `reqwest` client in 0.6.0. Can you test and let me know if it's still happening?

**Comment by nicklan** [comment]
closing for now. please re-open if this is still occurring (or open a new issue if you find something new)
