### ISSUE TITLE
Homebrew installation for MacOS

### ISSUE THREAD

**Issue by bygui86** [databricks/click#171]
Hi guys,

I like this tool. But for who does not want to install rust and cargo (because not used in the company), what about an easy installation with Homebrew on MacOS?

**Comment by nicklan** [comment]
I'd like to offer that, but I'm not a Mac user, so it would need to come from someone else. What would be involved in supporting that?

**Comment by bygui86** [comment]
@nicklan I don't think you should support macos specifically. In general it would be good to have an easier installation mode not requiring cargo. Something like "download the compiled executable and put it in your PATH".

**Comment by rockwotj** [comment]
It would be great if this project hosted precompiled binaries in the Releases page when tags are created. I think this would be pretty simple to add via: https://github.com/rust-build/rust-build.action

**Comment by nicklan** [comment]
This is done now, check the Release page :)
