### ISSUE TITLE
Allow log command without container when there is only one container

### ISSUE THREAD

**Issue by maver1ck** [databricks/click#19]
Right now we need to use container name when using logs always.
There is no need for that when there is only one container in the pod.

**Comment by nicklan** [comment]
Good idea, should be pretty easy.

**Comment by maver1ck** [comment]
Thanks a lot.
It's working great :)

**Comment by nicklan** [comment]
Sure, thanks for the feedback!

**Comment by maver1ck** [comment]
This tool is great.
I don't know how I was able to live without it :)
