### ISSUE TITLE
Couldn't find/load context, error:0308010C

### ISSUE THREAD

**Issue by ericdoomed** [databricks/click#195]
```
$ kubelet --version
Kubernetes v1.23.6
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04 LTS
Release:        22.04
Codename:       jammy
$ k config get-contexts
CURRENT   NAME                          CLUSTER      AUTHINFO           NAMESPACE
*         kubernetes-admin@kubernetes   kubernetes   kubernetes-admin
$ click --version
Click 0.6.0
$ click
[none] [none] [none] > context
 Context                       Api Server Address
════════════════════════════════════════════════════════
 kubernetes-admin@kubernetes   [no cluster for context]
────────────────────────────────────────────────────────
[none] [none] [none] > context kubernetes-admin@kubernetes
[WARN] Couldn't find/load context kubernetes-admin@kubernetes, now no current context. Error: Reqwest error: builder error: error:0308010C:digital envelope routines:inner_evp_generic_fetch:unsupported:../crypto/evp/evp_fetch.c:349:Global default library context, Algorithm (RC2-40-CBC : 0), Properties ()
```

**Comment by nicklan** [comment]
interesting, thanks for the report.

would it be possible for you to put your `.kube/config` file here (or at least the parts relevant to the `kubernetes-admin@kubernetes` cluster)? Obviously redact any sensitive secrets. I think click must just be not parsing the file correctly, but it's hard to know exactly why without seeing the file.

**Comment by libratiger** [comment]
hi, @nicklan I build with the v0.6.1, but I still see the following error

> mac verification failed during pkcs12 import wrong password

**Comment by wcasanova** [comment]
v. 0.6.2.613.g839dbcb 

still the same error

> ```
> $ kubelet --version
> Kubernetes v1.23.6
> $ lsb_release -a
> No LSB modules are available.
> Distributor ID: Ubuntu
> Description:    Ubuntu 22.04 LTS
> Release:        22.04
> Codename:       jammy
> $ k config get-contexts
> CURRENT   NAME                          CLUSTER      AUTHINFO           NAMESPACE
> *         kubernetes-admin@kubernetes   kubernetes   kubernetes-admin
> $ click --version
> Click 0.6.0
> $ click
> [none] [none] [none] > context
>  Context                       Api Server Address
> ════════════════════════════════════════════════════════
>  kubernetes-admin@kubernetes   [no cluster for context]
> ────────────────────────────────────────────────────────
> [none] [none] [none] > context kubernetes-admin@kubernetes
> [WARN] Couldn't find/load context kubernetes-admin@kubernetes, now no current context. Error: Reqwest error: builder error: error:0308010C:digital envelope routines:inner_evp_generic_fetch:unsupported:../crypto/evp/evp_fetch.c:349:Global default library context, Algorithm (RC2-40-CBC : 0), Properties ()
> ```
