### ISSUE TITLE
Describe on secret doesn't show token

### ISSUE THREAD

**Issue by maver1ck** [databricks/click#20]
This is regress in comparision to kubectl where describe show token value

**Comment by nicklan** [comment]
Seems reasonable, we can add that in

**Comment by maver1ck** [comment]
I checked describe -j but it shows base64 encoded version of token. So it's not what is needed.

**Comment by maver1ck** [comment]
Great work :)

**Comment by nicklan** [comment]
Hah, I was just too late with the PR :)  It'll show the token now when you do describe
