### ISSUE TITLE
Accessing a cluster without a cert

### ISSUE THREAD

**Issue by rampage644** [databricks/click#27]
Hello,

Thanks for such a nice project! Kudos!

While trying to connect to insecure cluster, `click` outputs "Can't do insecure-skip-tls-verify yet".
Obviously, it is not supported yet. Is there an estimate when such setups will be supported?

**Comment by gabel** [comment]
Especially for the Docker Edge version with Kubernetes build-in on a local machine (e.g. Mac OS) this is required.

**Comment by skeenan947** [comment]
Love this project!  Can't wait to use it, but this feature is pretty important - I can't make use of click without it.

**Comment by wieslaw-gat** [comment]
+1, as this sounds very useful.

As a side note: you can work around this limitation by passing ` --embed-certs=true` and `--certificate-authority=path_to_custom_cluster_crt` to `kubectl config set-cluster` instead of `--insecure-skip-tls-verify=true`

**Comment by rampage644** [comment]
@wieslaw-gat Thanks for a workaround!

**Comment by nicklan** [comment]
Yeah, the problem with insecure-skip-tls-verify is that it's only supported in much newer versions of Hyper, and doing that upgrade is a big project as they've moved everything over to tokio.  It's very much something I want to do asap, but will need to find the time too.  I will look at if there's a more hacky workaround to support this sooner.

**Comment by nicklan** [comment]
Actually, turns out it was easy to get a new enough version of rustls to support this.  Will merge support in a sec
