### ISSUE TITLE
[Bug] Click print "Private key data was invalid"

### ISSUE THREAD

**Issue by Hevienz** [databricks/click#33]
Click print "Private key data was invalid", but this private key can be used by kubectl and helm.

**Comment by farcaller** [comment]
Same problem here.

> [none] [none] [none] > context kubernetes-admin@kubernetes
> Private key data was invalid: ()

This is a vanilla kubeconfig generated by kubeadm.

**Comment by farcaller** [comment]
Specifically, `RSAKeyPair::from_der` fails in the step `5.i`. Can't debug further right now as lldb triggers a hilarious kernel memory leak and osx dies 🤦‍♂️

**Comment by farcaller** [comment]
Digging deeper, this starts to look like a ring problem to me (maybe related to https://github.com/briansmith/ring/issues/635 ?). 

`try!(q.verify_less_than(&p))` fails for me (`LIMBS_less_than(q, p)` returns 0). My pk has `q<p` though (verified with pycrypto).

**Comment by farcaller** [comment]
Got sidetracked. It is a ring bug.

```
                // XXX: |p < q| is actually OK, it seems, but our implementation
                // of CRT-based moduluar exponentiation used requires that
                // |q > p|. (|p == q| is just wrong.)
```

kubeadm generated keys have `p < q` (I looked into a wrong key in the previous comment)

**Comment by nicklan** [comment]
Ahh yes!  We ran into this at some point a long time ago and then moved away from those kinds of keys.

There is a general problem here that the Rust ecosystem has much stricter requirements around keys/certs than most other languages.  WebPKI also rejects a number of certs that other languages (i.e. go/python) accept happily.  

Trying to fix everything in Click is probably infeasible, but I will be pushing on upstream authors and looking at ways to improve this situation.

For this case, there is a PR out against ring, and once it merges we can update Click's dependencies and you should be good to go.  I'll leave this open to remind me to update ring asap.

**Comment by thedeeno** [comment]
@farcaller now that the above is merged into ring am I safe to assume once they do a release this issue will be resolved? Do we need something else?

**Comment by farcaller** [comment]
I suppose that it will work, but I suggest to wait and see.

**Comment by sibrahim001982** [comment]
Still getting the same error.

Any updates on this?

**Comment by sibrahim001982** [comment]
This is not only with minikube, same error with kubeadm-bootstraped clusters.
