### ISSUE TITLE
Tag versions in repo

### ISSUE THREAD

**Issue by mkw** [databricks/click#34]
I'd like to make a Homebrew formula for this, but they [require tagged releases](https://github.com/Homebrew/brew/blob/master/docs/Acceptable-Formulae.md).  Any chance that you could tag versions in git as they are released to crates.io?

**Comment by nicklan** [comment]
Yes for sure!  I will tag the next version which  should be coming out in the next few days.

**Comment by nicklan** [comment]
Done.  The v0.3.2 tag now exists

**Comment by mkw** [comment]
Thanks -- Homebrew PR submitted: https://github.com/Homebrew/homebrew-core/pull/26177
