### ISSUE TITLE
logs not working

### ISSUE THREAD

**Issue by omerlin** [databricks/click#43]
hello,

I'm inside a pod and i want to see the logs
[admin-context] [smdp4] [consumer-profile-stock-1387439186-s6pvb] > logs
error: The following required arguments were not provided:
    <container>

USAGE:
    logs [FLAGS] [OPTIONS] <container>

For more information try --help

So i tried to give the container name even if i thing we should not need (we are "in" the pod):
[admin-context] [smdp4] [consumer-profile-stock-1387439186-s6pvb] > logs consumer-profile-stock
Hyper error: failed to lookup address information: Name or service not known

Any idea ?
cheers

**Comment by nicklan** [comment]
Hrmm that's odd.  So for pods with one container the next release (or master) will default to that container for logs (see #25).

The second error is odd.  could you paste the output of the `containers` command when you have selected that pod.  Also, how many nodes are in your cluster?

**Comment by nicklan** [comment]
I'm pretty sure I fixed this in #46.  If you're building click yourself, would you mind updating to latest master and testing?

Thanks!

**Comment by omerlin** [comment]
Hello Nick,
Rebuilding from source works well and solve the logs issue.
Thanks a lot
cheers

**Comment by nicklan** [comment]
great, glad to hear it.  thanks for closing :)
