### ISSUE TITLE
Support for Custom Resources

### ISSUE THREAD

**Issue by maver1ck** [databricks/click#70]
Kubernetes has ability to define Custom Resources via CRD.
We'd like to list and describe those resources.
Sample resources:
TFJob
https://www.kubeflow.org/docs/guides/components/tftraining/

Certificate Issuer
https://github.com/jetstack/cert-manager/blob/master/docs/reference/issuers.rst

Manual:
https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/

**Comment by nicklan** [comment]
please see the new `crd` command
